use databaseingexis;
-- =================================================
-- create VIEW muestra_usuer as
-- select 
--     muestra.id_muestra,
--     muestra.resultado,
--     muestra.fecha_prog,
--     muestra.identificador,
--     usuarios.apodo,
--     log_usuarios.img_log
-- from
--     muestra,
--     usuarios,
--     log_usuarios
-- where
--     muestra.id_usuario = log_usuarios.id_usuario AND
--     muestra.id_usuario = usuarios.id_usuario AND
--     muestra.resultado != '??';
-- =================================================
-- create view info_elemento as
-- select 
--     elemento.id_elemento,
--     elemento.nombre,
--     elemento.observaciones,
--     elemento.fecha_muestreo,
--     muestra.id_muestra,
--     muestra.identificador,
--     muestra.resultado,
--     muestra.fecha_prog
-- from 
--     elemento inner join muestra on elemento.id_elemento = muestra.id_elemento 
-- ORDER BY  muestra.fecha_prog ASC;
-- =================================================
-- =================================================