-- use databaseingexis;
-- --======================================--
-- CREATE FUNCTION existencia_elemento_in_obra(id_obra int, nombre varchar(50)) returns VARCHAR(5)
-- begin 
--     declare respuesta int;
--     SELECT elemento.id_elemento into respuesta from elemento WHERE elemento.id_obra = Id_obra and elemento.nombre = nombre;
--     if respuesta != 0 then
--         return 'true';
--     else
--         return 'false';
--     end if;
-- end
-- --======================================--
-- create FUNCTION Obra_id_by_nombre(nombre VARCHAR(50)) RETURNS  int
-- begin
--     declare respuesta int;
--     SELECT obras.id_obra into respuesta from obras where obras.nombre = nombre;
--     return respuesta;
-- end
-- --======================================--
-- CREATE FUNCTION existencia_identificador(ident varchar(10)) returns VARCHAR(5)
-- begin 
--     declare respuesta int;
--     SELECT muestra.id_muestra into respuesta from muestra where muestra.identificador = ident;
--     if respuesta != 0 then
--         return 'true';
--     else
--         return 'false';
--     end if;
-- end
-- --======================================--
-- create FUNCTION ElemMues_idMues_by_ident(ident varchar(10)) returns int
-- begin
--     declare respuesta int;
--     SELECT muestra.id_muestra into respuesta from muestra where muestra.identificador = ident;
--     return respuesta;
-- end
-- --======================================--