-- use databaseingexis;
-- -- ======================================--
-- create FUNCTION id_by_correo_Clientes(correo varchar(50)) returns int
-- begin
--     declare salida int;
--     select clientes.id_clientes into salida from clientes where clientes.email = correo;
--     return salida;
-- end
-- -- ======================================--
-- CREATE FUNCTION img_Client_by_correo(correo varchar(50)) returns varchar(100)
-- BEGIN
--     declare salida varchar(100);
--     select clientes.img into salida from clientes where clientes.email = correo;
--     return salida;
-- end